import { NavItem, FeatureItem, StatItem, TestimonialItem, FAQItem } from '../types';

export const SITE_CONFIG = {
  name: 'AI Loan Advisory Agent',
  description: 'Enterprise AI Agent for Policy-Backed Intelligent Loan Advice',
  url: 'https://loan-ai.example.com',
  author: 'Loan AI Engineering Team',
};

export const NAV_ITEMS: NavItem[] = [
  { label: 'Home', href: '/' },
  { label: 'Features', href: '/features' },
  { label: 'How It Works', href: '/#how-it-works' },
  { label: 'About', href: '/about' },
  { label: 'Contact', href: '/contact' },
];

export const FEATURES: FeatureItem[] = [
  {
    id: 'policy-rag',
    title: 'Policy-Backed RAG',
    description: 'Instant answers grounded directly in official bank guidelines and lending documentation with zero hallucination.',
    iconName: 'FileText',
    tag: 'Accuracy',
  },
  {
    id: 'semantic-search',
    title: 'Semantic Search Engine',
    description: 'Query lending clauses using plain conversational language with high-dimensional vector search accuracy.',
    iconName: 'Search',
    tag: 'Speed',
  },
  {
    id: 'eligibility-preview',
    title: 'Eligibility Intelligence',
    description: 'Real-time pre-assessment checking borrower parameters against complex multi-tier risk frameworks.',
    iconName: 'CheckCircle2',
    tag: 'Precision',
  },
  {
    id: 'emi-calculator',
    title: 'Dynamic EMI Simulator',
    description: 'Calculate principal, interest schedule, tax deductions, and early repayment savings interactively.',
    iconName: 'Calculator',
    tag: 'Utility',
  },
  {
    id: 'ocr-ingestion',
    title: 'Document OCR Engine',
    description: 'Extract income statements, tax files, and bank records with optical character recognition.',
    iconName: 'ScanText',
    tag: 'Automation',
  },
  {
    id: 'enterprise-security',
    title: 'Bank-Grade Security',
    description: 'AES-256 encrypted payload handling with strict role-based access tokens and compliance audit logs.',
    iconName: 'ShieldCheck',
    tag: 'Compliance',
  },
];

export const STATS: StatItem[] = [
  {
    id: '1',
    value: 99.4,
    suffix: '%',
    label: 'Answer Precision',
    description: 'Verified against actual bank underwriting guidelines',
  },
  {
    id: '2',
    value: 780,
    prefix: '< ',
    suffix: 'ms',
    label: 'Query Latency',
    description: 'Sub-second response time for complex policy lookups',
  },
  {
    id: '3',
    value: 500,
    suffix: '+',
    label: 'Policy Manuals',
    description: 'Indexed across retail, mortgage, and commercial credit',
  },
  {
    id: '4',
    value: 2.4,
    prefix: '$',
    suffix: 'B+',
    label: 'Loan Volume Advised',
    description: 'Evaluated under strict institutional risk limits',
  },
];

export const TESTIMONIALS: TestimonialItem[] = [
  {
    id: 't1',
    quote: 'This AI advisory agent reduced our credit officer lookup time from 45 minutes to under 5 seconds. The source citations build instant confidence.',
    author: 'Sarah Jenkins',
    role: 'Chief Risk Officer',
    company: 'Apex Financial Services',
    rating: 5,
  },
  {
    id: 't2',
    quote: 'The accuracy of policy extraction is unmatched. Our loan advisors can navigate complex multi-regional lending rules effortlessly.',
    author: 'Marcus Vance',
    role: 'VP of Retail Banking',
    company: 'Crestline Capital',
    rating: 5,
  },
  {
    id: 't3',
    quote: 'Engineered with clean architectural discipline. The API response times and structured error handling are truly production-ready.',
    author: 'Elena Rostova',
    role: 'Lead Financial Systems Architect',
    company: 'FinTech Dynamics',
    rating: 5,
  },
];

export const FAQS: FAQItem[] = [
  {
    id: 'faq-1',
    question: 'How does the AI Loan Advisory Agent verify its answers?',
    answer: 'Every answer generated by the agent is retrieved directly from indexed policy documents with exact section citations, ensuring full compliance and eliminating hallucinated responses.',
    category: 'Accuracy',
  },
  {
    id: 'faq-2',
    question: 'Can the agent handle custom institutional policy guidelines?',
    answer: 'Yes. Institutional policy sets, underwriting criteria, and regional rate tables can be indexed seamlessly via our secure enterprise pipeline.',
    category: 'Integration',
  },
  {
    id: 'faq-3',
    question: 'Is user financial data kept secure and compliant?',
    answer: 'Absoluty. Data is processed through bank-grade encryption with zero persistent storage of sensitive unencrypted PII.',
    category: 'Security',
  },
  {
    id: 'faq-4',
    question: 'What loan products are supported?',
    answer: 'The system supports Home Loans, Personal Loans, Business Credit, Commercial Mortgages, Vehicle Loans, and Education Loans.',
    category: 'Products',
  },
];
